name: SEAndroid v100.0.30 Build

on:
  push:
    branches:
      - v100.0.30
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "V100.0.30 workflow syntax OK"
